# Configurazione per test locale con Jekyll

# Permetti a Jekyll di servire anche file che iniziano con un punto (come .nojekyll)
include:
  - .htaccess
  - .nojekyll

# Disabilita la generazione automatica di pagine da Jekyll (serve solo file statici)
exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - yarn.lock
  - .github
  - assets/*.psd
  - assets/*.ai
  - assets/*.svg

# Imposta la cartella di destinazione (opzionale, default: _site)
destination: _site

# Imposta la baseurl per la sottocartella (importante per testare come su GitHub Pages)
baseurl: "/calcolatore_40k"

# Imposta l'url del sito (opzionale, utile per testare link assoluti)
url: "http://localhost:4000"
